### ISSUE TITLE
RUSTSEC-2016-0005: rust-crypto: rust-crypto is unmaintained; switch to a modern alternative

### ISSUE THREAD

**Issue by sciguy16** [citronneur/rdp-rs#2]
There's a RustSec advisory for the rust-crypto dependency which has been unmaintained since 2016. It's probably worth considering switching to crates from the [RustCrypto](https://github.com/RustCrypto) project in the longer term.

https://rustsec.org/advisories/RUSTSEC-2016-0005

**Comment by citronneur** [comment]
Ok i will check

**Comment by citronneur** [comment]
I remove the dependency, It will be available on the 0.1.1.
Thanks

**Comment by sciguy16** [comment]
Looks good, thanks for updating :)
